// Generated by CoffeeScript 1.10.0
(function() {
  var canvas, gl, init, initWebGL;

  canvas = null;

  gl = null;

  init = function() {
    canvas = document.getElementById("glcanvas");
    initWebGL();
    if (gl) {
      glCamera.bindMouseEvents(canvas);
      gl.clearColor(0.0, 0.0, 0.0, 1.0);
      gl.clearDepth(1.0);
      return gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
    }
  };

  initWebGL = function() {
    var error, error1;
    try {
      gl = (canvas.getContext("webgl")) || canvas.getContext("experimental-webgl");
    } catch (error1) {
      error = error1;
      console.log(error);
    }
    if (!gl) {
      alert("Unable to initialize WebGL. Your browser may not suppert it.");
      return gl = null;
    }
  };

  window.glContext = {
    init: init
  };

}).call(this);

//# sourceMappingURL=context.js.map
